### ISSUE TITLE
Prod Revision Going Down - Log Error

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-platform#1025]
**Description**

Investigate, why is this occurring?:
```
7/14/2022, 8:34:40 PM service:web-app error [MessagingConnection] Messaging connection emitted an error
```
```
7/14/2022, 8:34:40 PM service:web-app error [MessagingConnection] Error: Unexpected close
 at succeed (/ibm/services/web-app/dist/out.js:41092:64)
 at onOpenOk (/ibm/services/web-app/dist/out.js:41081:9)
 at /ibm/services/web-app/dist/out.js:41014:13
 at /ibm/services/web-app/dist/out.js:41008:13
 at TLSSocket.recv (/ibm/services/web-app/dist/out.js:41238:11)
 at Object.onceWrapper (node:events:641:28)
 at TLSSocket.emit (node:events:527:28)
 at emitReadable_ (node:internal/streams/readable:578:12)
 at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
```
7/14/2022, 8:34:40 PM service:web-app warn [MessagingConnection] Exception caught closing channel while trying to close messaging connection
```
```
7/14/2022, 8:34:40 PM service:web-app warn [MessagingConnection] IllegalOperationError: Channel closed
  at ConfirmChannel.<anonymous> (/ibm/services/web-app/dist/out.js:41682:15)
  at ConfirmChannel.C.closeBecause (/ibm/services/web-app/dist/out.js:41722:12)
  at /ibm/services/web-app/dist/out.js:42220:23
  at node:internal/util:360:7
  at new Promise (<anonymous>)
  at node:internal/util:346:12
  at ConfirmChannel.close (/ibm/services/web-app/dist/out.js:42221:11)
  at MessagingConnection.close (/ibm/services/web-app/dist/out.js:42477:32)
  at runMicrotasks (<anonymous>)
```

**Steps to reproduce**

How do we reproduce the error? Please be as specific as you can.

N/A

**Comment by jdharvey-ibm** [comment]
Looking through the logs, I noticed that our service received a `SIGTERM` signal from Code Engine, but no reason for the signal was given, and no service was recreated after the service stopped executing (because of the signal). This caused an outage with no debug info provided by Code Engine as to why this was the case. Could have been a resource constraint, but no information was provided to it.
