### ISSUE TITLE
Production Next.js build is breaking

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-platform#132]
### Description

```shell
FILE WRITE github.ibm.com/matt-rosno/carbon-for-ibm-dotcom/master/packages/styles/scss/components/card/docs/card.svg
FILE WRITE github.ibm.com/matt-rosno/carbon-for-ibm-dotcom/master/packages/styles/scss/components/content-block-simple/docs/content_block_simple.svg
FILE WRITE github.ibm.com/matt-rosno/carbon-for-ibm-dotcom/master/packages/styles/scss/components/back-to-top/docs/back_to_top.svg

Error occurred prerendering page "/en-US/assets/libraries". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Empty file
    at syncFileToBuffer (/Users/mattrosno/Git/carbon-platform/node_modules/plaiceholder/dist/index.js:4372:13)
    at imageSize (/Users/mattrosno/Git/carbon-platform/node_modules/plaiceholder/dist/index.js:4408:22)
    at getImageSize (/Users/mattrosno/Git/carbon-platform/node_modules/plaiceholder/dist/index.js:4443:7)
    at loadImage (/Users/mattrosno/Git/carbon-platform/node_modules/plaiceholder/dist/index.js:4494:21)
    at getImage (/Users/mattrosno/Git/carbon-platform/node_modules/plaiceholder/dist/index.js:4553:13)
    at getPlaiceholder (/Users/mattrosno/Git/carbon-platform/node_modules/plaiceholder/dist/index.js:4630:13)
    at /Users/mattrosno/Git/carbon-platform/services/web-app/.next/server/chunks/744.js:658:77
    at Array.map (<anonymous>)
    at getImagePlaceholders (/Users/mattrosno/Git/carbon-platform/services/web-app/.next/server/chunks/744.js:656:48)
    at async getLibraryAssets (/Users/mattrosno/Git/carbon-platform/services/web-app/.next/server/chunks/744.js:554:29)
info  - Generating static pages (13/13)

> Build error occurred
Error: Export encountered errors on following paths:
        /en-US/assets/libraries
    at /Users/mattrosno/Git/carbon-platform/node_modules/next/dist/export/index.js:493:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/Users/mattrosno/Git/carbon-platform/node_modules/next/dist/trace/trace.js:74:20)
    at async /Users/mattrosno/Git/carbon-platform/node_modules/next/dist/build/index.js:962:17
    at async Span.traceAsyncFn (/Users/mattrosno/Git/carbon-platform/node_modules/next/dist/trace/trace.js:74:20)
    at async /Users/mattrosno/Git/carbon-platform/node_modules/next/dist/build/index.js:836:13
    at async Span.traceAsyncFn (/Users/mattrosno/Git/carbon-platform/node_modules/next/dist/trace/trace.js:74:20)
    at async Object.build [as default] (/Users/mattrosno/Git/carbon-platform/node_modules/next/dist/build/index.js:82:25)
```

### Steps to reproduce

`main` branch. Temporarily deleted all pages but `/pages/libraries.js` to prevent any potential race conditions.

![image](https://user-images.githubusercontent.com/1691245/142282495-7817843a-f6d4-4cfe-83f4-13fc6fbc211e.png)

**Comment by mattrosno** [comment]
Found an empty SVG file:
![image](https://user-images.githubusercontent.com/1691245/142284639-3eb0c0ad-1a8d-4c0e-83e1-94370efe21be.png)

**Comment by mattrosno** [comment]
```shell
FILE WRITE github.ibm.com/matt-rosno/carbon-for-ibm-dotcom/master/packages/styles/scss/components/back-to-top/docs/back_to_top.svg
[   =] info  - Generating static pages (12/13)transform failed [Error: Input file contains unsupported image format]

Error occurred prerendering page "/en-US/assets/libraries". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Input file contains unsupported image format
info  - Generating static pages (13/13)

> Build error occurred
Error: Export encountered errors on following paths:
        /en-US/assets/libraries
    at /Users/mattrosno/Git/carbon-platform/node_modules/next/dist/export/index.js:493:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/Users/mattrosno/Git/carbon-platform/node_modules/next/dist/trace/trace.js:74:20)
    at async /Users/mattrosno/Git/carbon-platform/node_modules/next/dist/build/index.js:962:17
    at async Span.traceAsyncFn (/Users/mattrosno/Git/carbon-platform/node_modules/next/dist/trace/trace.js:74:20)
    at async /Users/mattrosno/Git/carbon-platform/node_modules/next/dist/build/index.js:836:13
    at async Span.traceAsyncFn (/Users/mattrosno/Git/carbon-platform/node_modules/next/dist/trace/trace.js:74:20)
    at async Object.build [as default] (/Users/mattrosno/Git/carbon-platform/node_modules/next/dist/build/index.js:82:25)
```

Something to do with images for sure. `Error: Input file contains unsupported image format`
